name: Encrypt Zip to Ozip and Upload

on:
  push:
    branches: [ main ]

jobs:
  encrypt_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y openssl zip
      - name: Download and Encrypt Zip file
        run: |
          curl -L -o file.zip "https://s3.ap-south-1.amazonaws.com/blob-ap-south-1-ukyez4/sara/b7/b75d/b75d54cf-e54f-4181-ae10-a7aed02eda2d.bin?response-content-disposition=attachment%3B%20filename%3D%22build.zip%22&response-content-type=application%2Fzip&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4DM2EY46SOWUMUP4%2F20230408%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20230408T172748Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=29a76ede1b475b1849c66a74be479d451930be1816d27715ce31591da40e1df4"
          openssl enc -aes-256-cbc -salt -in file.zip -out file.ozip -k "Abhi@1234"
      - name: Upload Encrypted file to Bash Upload
        run: |
          curl -X POST --data-binary @file.ozip https://bashupload.com -H "Max-Downloads: 1" -H "Max-Days: 1"
